//
//  HomeView.swift
//  IslandPet
//
//  Redesigned home dashboard. The "front door" of the app — has to do four
//  things in the first second:
//
//   1. Make the user feel something about the pet.
//   2. Tell them where they stand (level, streak, coins, today).
//   3. Give them an obvious next action (start focus).
//   4. Reward returning visits with subtle freshness (greeting, time-of-day).
//
//  Design choices:
//   • The pet zone is the hero. It bobs, blinks, and reacts to taps with
//     a squish animation + petPoke haptic. Tappable feels alive.
//   • The greeting is generated by the personality engine, so every user
//     sees a slightly different line tuned to their pet's traits.
//   • Cards cascade in on appear (CascadeIn) — a 250ms detail that reads
//     as "considered" without users knowing why.
//   • A +XP badge floats up after each focus completion (XPGainBadge).
//

import SwiftUI
import SwiftData

struct HomeView: View {
    @EnvironmentObject private var petVM: PetViewModel
    @EnvironmentObject private var timerVM: TimerViewModel
    @EnvironmentObject private var appState: AppState

    @Query(filter: HomeView.todayPredicate(),
           sort: \FocusSession.startedAt, order: .reverse)
    private var todaysSessions: [FocusSession]

    // Pet tap interaction
    @State private var petTapSquish: CGFloat = 1.0
    @State private var petTapID: UUID?

    // XP gain micro-interaction
    @State private var lastXPAmount: Int = 0
    @State private var xpGainTrigger: UUID?
    @State private var lastSessionCount: Int = 0

    var body: some View {
        ZStack {
            BackgroundAurora()

            ScrollView {
                VStack(spacing: Tokens.Space.l) {
                    header.cascadeIn(index: 0)
                    petStage.cascadeIn(index: 1)
                    statsGrid.cascadeIn(index: 2)
                    quickActions.cascadeIn(index: 3)
                    todayCard.cascadeIn(index: 4)
                    Spacer(minLength: Tokens.Space.xxl)
                }
                .padding(.horizontal, Tokens.Space.m + 2)
                .padding(.top, Tokens.Space.s)
            }

            // Top-level overlays
            VStack {
                if petVM.showLevelUpToast {
                    ToastView(icon: "arrow.up.circle.fill",
                              title: "Level up!",
                              subtitle: "You reached level \(petVM.pet?.level ?? 0)")
                    .transition(.move(edge: .top).combined(with: .opacity))
                }
                Spacer()
            }
            .animation(.iSmooth, value: petVM.showLevelUpToast)
            .padding(.top, Tokens.Space.s + 4)

            // The XP gain confetti, floating above the pet
            VStack {
                Spacer().frame(height: 200)
                XPGainBadge(amount: lastXPAmount, trigger: $xpGainTrigger)
                Spacer()
            }
            .allowsHitTesting(false)
        }
        .onChange(of: todaysSessions.count) { old, new in
            // A new completed session arrived — show the XP gain.
            if new > old, let last = todaysSessions.first, last.completed {
                lastXPAmount = last.xpEarned
                xpGainTrigger = UUID()
            }
            lastSessionCount = new
        }
    }

    // MARK: - Computed today stats

    private var todayCompletedCount: Int {
        todaysSessions.filter(\.completed).count
    }

    private var todayFocusMinutes: Int {
        todaysSessions.reduce(0) { $0 + ($1.actualDurationSeconds / 60) }
    }

    private var todayXP: Int {
        todaysSessions.filter(\.completed).reduce(0) { $0 + $1.xpEarned }
    }

    private var greeting: String {
        guard let pet = petVM.pet else { return "Welcome" }
        return PetVoice(pet: pet).greeting()
    }

    // MARK: - Sections

    private var header: some View {
        HStack(alignment: .center) {
            VStack(alignment: .leading, spacing: 2) {
                Text(greeting)
                    .font(Theme.body(15))
                    .foregroundStyle(Theme.text.secondary)
                    .lineLimit(1)
                Text(petVM.pet?.name ?? "IslandPet")
                    .font(Theme.display(28))
            }
            Spacer()

            // Streak + coins pill stack
            HStack(spacing: Tokens.Space.s) {
                StatBadge(
                    icon: "flame.fill",
                    value: "\(petVM.settings?.currentStreak ?? 0)",
                    tint: .orange
                )
                StatBadge(
                    icon: "circle.hexagongrid.fill",
                    value: "\(petVM.settings?.coins ?? 0)",
                    tint: Theme.secondary
                )
            }
        }
        .padding(.top, Tokens.Space.s)
    }

    private var petStage: some View {
        VStack(spacing: Tokens.Space.m - 2) {
            if let pet = petVM.pet {
                ZStack {
                    // soft platform shadow under pet
                    Ellipse()
                        .fill(.black.opacity(0.10))
                        .frame(width: 140, height: 14)
                        .blur(radius: 8)
                        .offset(y: 95)

                    PetSprite(species: pet.species,
                              stage: pet.stage,
                              mood: pet.mood,
                              size: 180)
                        .breathing()
                        .scaleEffect(petTapSquish)
                }
                .frame(height: 220)
                .contentShape(Rectangle())
                .onTapGesture { tapPet() }

                HStack(spacing: Tokens.Space.xs + 2) {
                    Text("Lv \(pet.level)").pill(Theme.accent)
                    Text(pet.stage.rawValue.capitalized)
                        .font(Theme.caption())
                        .foregroundStyle(Theme.text.tertiary)
                }

                XPBar(current: pet.xpIntoLevel, total: pet.xpForNextLevel)
                    .padding(.horizontal, Tokens.Space.l)
            }
        }
        .padding(.vertical, Tokens.Space.m + 2)
        .frame(maxWidth: .infinity)
        .background(GlassCard())
    }

    private var statsGrid: some View {
        HStack(spacing: Tokens.Space.s + 4) {
            if let pet = petVM.pet {
                StatPill(icon: "heart.fill", title: "Mood",
                         value: pet.happiness, tint: .pink)
                StatPill(icon: "fork.knife", title: "Hunger",
                         value: pet.hunger, tint: .orange)
                StatPill(icon: "moon.zzz.fill", title: "Energy",
                         value: pet.energy, tint: .indigo)
            }
        }
    }

    private var quickActions: some View {
        HStack(spacing: Tokens.Space.s + 4) {
            ActionTile(icon: "play.fill", label: "Focus", tint: Theme.accent) {
                appState.selectedTab = .timer
            }
            ActionTile(icon: "fork.knife", label: "Feed", tint: .orange) {
                petVM.feed()
            }
            ActionTile(icon: "sparkles", label: "Play", tint: .pink) {
                petVM.play()
            }
            ActionTile(icon: "moon.fill", label: "Rest", tint: .indigo) {
                petVM.rest()
            }
        }
    }

    private var todayCard: some View {
        VStack(alignment: .leading, spacing: Tokens.Space.s + 4) {
            HStack {
                Text("Today").font(Theme.title(20))
                Spacer()
                if todayCompletedCount > 0 {
                    Label("\(todayCompletedCount) done", systemImage: "checkmark.seal.fill")
                        .pill(Theme.success)
                }
            }
            HStack {
                StatChip(icon: "timer", label: "Sessions",
                         value: "\(todayCompletedCount)")
                StatChip(icon: "clock.fill", label: "Focus time",
                         value: formatMinutes(todayFocusMinutes))
                StatChip(icon: "star.fill", label: "XP earned",
                         value: "\(todayXP)")
            }
        }
        .padding(Tokens.Space.m)
        .frame(maxWidth: .infinity, alignment: .leading)
        .background(GlassCard())
    }

    // MARK: - Interactions

    private func tapPet() {
        // Squish-and-rebound + organic haptic. The "polish" detail.
        HapticsService.shared.petPoke()
        withAnimation(.iSnap) { petTapSquish = 0.92 }
        Task {
            try? await Task.sleep(nanoseconds: 110_000_000)
            await MainActor.run {
                withAnimation(.iBouncy) { petTapSquish = 1.0 }
            }
        }
        // Side effect: tiny mood bump
        petVM.play()
    }

    private func formatMinutes(_ m: Int) -> String {
        if m < 60 { return "\(m)m" }
        let h = m / 60; let rem = m % 60
        return rem == 0 ? "\(h)h" : "\(h)h \(rem)m"
    }

    static func todayPredicate() -> Predicate<FocusSession> {
        let cal = Calendar.current
        let start = cal.startOfDay(for: .now)
        let end = cal.date(byAdding: .day, value: 1, to: start) ?? start
        return #Predicate<FocusSession> { s in
            s.startedAt >= start && s.startedAt < end
        }
    }
}

// MARK: - Subviews

private struct StatBadge: View {
    let icon: String
    let value: String
    let tint: Color
    var body: some View {
        HStack(spacing: Tokens.Space.xs + 2) {
            Image(systemName: icon).foregroundStyle(tint)
            Text(value).font(Theme.title(16))
        }
        .padding(.horizontal, Tokens.Space.s + 4)
        .padding(.vertical, Tokens.Space.s)
        .background(GlassCard())
    }
}

private struct XPBar: View {
    let current: Int
    let total: Int
    var body: some View {
        VStack(alignment: .leading, spacing: Tokens.Space.xs) {
            HStack {
                Text("XP")
                    .font(Theme.caption(12))
                    .foregroundStyle(Theme.text.secondary)
                Spacer()
                Text("\(current) / \(total)")
                    .font(Theme.caption(12))
                    .foregroundStyle(Theme.text.secondary)
                    .contentTransition(.numericText())
            }
            ProgressView(value: Double(current), total: Double(total))
                .progressViewStyle(StatBarStyle(tint: Theme.accent))
                .frame(height: 10)
        }
    }
}

private struct ActionTile: View {
    let icon: String
    let label: String
    let tint: Color
    let action: () -> Void

    @State private var pressed = false

    var body: some View {
        Button(action: { HapticsService.shared.tap(); action() }) {
            VStack(spacing: Tokens.Space.xs + 2) {
                Image(systemName: icon)
                    .font(.system(size: 22, weight: .semibold))
                    .foregroundStyle(tint)
                Text(label).font(Theme.caption())
            }
            .frame(maxWidth: .infinity)
            .padding(.vertical, Tokens.Space.m)
            .background(GlassCard())
            .scaleEffect(pressed ? 0.96 : 1)
            .animation(.iSnap, value: pressed)
        }
        .buttonStyle(.plain)
        .pressEvents(onPress: { pressed = true }, onRelease: { pressed = false })
    }
}

private struct StatChip: View {
    let icon: String
    let label: String
    let value: String
    var body: some View {
        VStack(alignment: .leading, spacing: Tokens.Space.xs) {
            Image(systemName: icon).foregroundStyle(Theme.text.secondary)
            Text(value)
                .font(Theme.title(18))
                .contentTransition(.numericText())
            Text(label)
                .font(Theme.caption(12))
                .foregroundStyle(Theme.text.secondary)
        }
        .frame(maxWidth: .infinity, alignment: .leading)
    }
}
